### ISSUE TITLE
Download/load just a feature in JOSM/iD

### ISSUE THREAD

**Issue by ddkpisme** [nrotstan/osmcha-frontend#1]
### Idea/Description

Sometimes it's useful to inspect a single feature (or a couple features) out of a changeset of many features. This gives users greater flexibility in how they choose to review the data. Currently users are limited to downloading the entirety of the changeset itself. They cannot click on individual features on the map and quickly download them without a few additional steps.

### Ask

Add a button next to OSM and Deep History to download a feature directly to JOSM/iD when you have it selected on the visual map.

### Notes

![Screen Shot 2019-06-21 at 4 10 56 PM](https://user-images.githubusercontent.com/20778284/67883516-7819b300-fb01-11e9-8e6d-c2539ed10a5d.png)

**Comment by nrotstan** [comment]
PR osmlab/changeset-map#192 submitted

**Comment by ddkpisme** [comment]
Awesome! Two points here we might consider:

- Closing the JOSM remote window after it contacts JOSM (Will create another ticket)
- Distinguishing the difference between "Open With" at the top of the page with the one shown one the feature. 
    - Something like "Open Changeset With" | "Open Feature With"

**Comment by ddkpisme** [comment]
https://github.com/osmlab/changeset-map/pull/199
