### ISSUE TITLE
Include a PeWu history link for features

### ISSUE THREAD

**Issue by ddkpisme** [nrotstan/osmcha-frontend#6]
### Idea/Description

It would be helpful to get a link for https://pewu.github.io/osm-history/#/ as an option when selecting features. Possibly next to where the Deep History button exists. This would help in seeing version history of features by sticking within a browser. Would decrease the need to jump into JOSM and run attic queries.

### Ask

Include a PeWu history link for features next to the Deep History button.

### Notes

- Existing issue: https://github.com/mapbox/osmcha-frontend/issues/334

**Comment by nrotstan** [comment]
PR osmlab/changeset-map#192 submitted

**Comment by ddkpisme** [comment]
This works great! Makes sense to consolidate it into a dropdown list.
